logLevel = "DEBUG"

defaultEntryPoints = ["http"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = false

[file]
[backends]
# OSHDE-TRAEFIK-BACKENDS
[frontends]
# OSHDE-TRAEFIK-FRONTENDS